{"name": "test_new_customer_a1_error_5", "status": "passed", "description": "新增账户开户失败的用例", "attachments": [{"name": "log", "source": "1be5b9ba-db39-4e52-a019-8246c5d68700-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "93603842-5f1c-44f8-afc8-1a1c99030eae-attachment.txt", "type": "text/plain"}], "start": 1617349327140, "stop": 1617349329581, "uuid": "255e3d4e-73f6-4d9f-ac83-da45a1c59754", "historyId": "9c59dec0712f0e398643990b73f32e02", "testCaseId": "08ee2d345287604bed987373f9e63ec7", "fullName": "tests.test_a6_newclientregister.TestNewCustomerAccount#test_new_customer_a1_error_5", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a6_newclientregister"}, {"name": "subSuite", "value": "TestNewCustomerAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a6_newclientregister"}]}