{"name": "test_capital_1_error_1", "status": "passed", "description": "新增资金账户失败的用例", "attachments": [{"name": "log", "source": "cf9fa385-e5b4-4ef2-b7ed-48171056c907-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "262b3d33-9c8f-4ca3-90d3-611fa02d2e8e-attachment.txt", "type": "text/plain"}], "start": 1617349292740, "stop": 1617349294137, "uuid": "fe784ad8-c061-48a0-aea2-a6212c35cf40", "historyId": "4a2ca26c94cac53e33667125d736bdac", "testCaseId": "6d8f6585f920e0766651c98a49da9431", "fullName": "tests.test_a5_addfundaccount.TestNewlyCompany#test_capital_1_error_1", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a5_addfundaccount"}, {"name": "subSuite", "value": "TestNewlyCompany"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a5_addfundaccount"}]}