{"name": "test_company_1_error_3", "status": "passed", "description": "新增经济公司失败的用例", "attachments": [{"name": "log", "source": "2a1da8e3-466c-4a68-8f02-30f0eaeaf53a-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "7a561cb7-c09e-4d95-bb6a-c2a3bfa18d3f-attachment.txt", "type": "text/plain"}], "start": 1617349214522, "stop": 1617349215848, "uuid": "f878dfca-63ee-4ff3-bfec-281b4ea1e57d", "historyId": "ac52f5d4e3595318192563d8aaeabb64", "testCaseId": "5437acc517702eecb86b2ae50131b5d1", "fullName": "tests.test_a2_newbrokeragefirms.TestNewlyCompany#test_company_1_error_3", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a2_newbrokeragefirms"}, {"name": "subSuite", "value": "TestNewlyCompany"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a2_newbrokeragefirms"}]}