{"name": "test_openanaccount_a1_error_5", "status": "passed", "description": "账户开户失败的用例", "attachments": [{"name": "log", "source": "1a6399aa-879e-4d02-92a1-2ffdb95bc010-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "882dcd50-cf2f-4ccf-a771-51e540464703-attachment.txt", "type": "text/plain"}], "start": 1617349383210, "stop": 1617349385445, "uuid": "e95402ad-7cba-4de8-9b5c-1ffc88d6847f", "historyId": "c00fd83db7bc4e298db58e2fd72797de", "testCaseId": "56e8a958d1f821ab6b3dc9e3819db1f0", "fullName": "tests.test_a8_the_customer_account.TestTheCustomerAccount#test_openanaccount_a1_error_5", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a8_the_customer_account"}, {"name": "subSuite", "value": "TestTheCustomerAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a8_the_customer_account"}]}