{"name": "test_new_customer_a1_error_4", "status": "passed", "description": "新增账户开户失败的用例", "attachments": [{"name": "log", "source": "bc49712d-0cc3-4b19-9dc3-997b31acb715-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "636a6e82-bfe4-4c1e-852d-b09d5f8498b0-attachment.txt", "type": "text/plain"}], "start": 1617349325703, "stop": 1617349327138, "uuid": "49a9ae98-2270-4a33-a68d-a20c39eae802", "historyId": "c1e6f4b1f602240cb951fecbe504b23f", "testCaseId": "e8af3143c0cc489f85aaa7b8042e32da", "fullName": "tests.test_a6_newclientregister.TestNewCustomerAccount#test_new_customer_a1_error_4", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a6_newclientregister"}, {"name": "subSuite", "value": "TestNewCustomerAccount"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a6_newclientregister"}]}