{"name": "test_login_1_error_2", "status": "passed", "description": "登录失败", "attachments": [{"name": "log", "source": "41365d7a-888f-4c28-968d-1332c976ce9c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "0a4be111-75e9-4275-abae-a0e7f35193a1-attachment.txt", "type": "text/plain"}], "start": 1617349193793, "stop": 1617349194567, "uuid": "67f379c8-5342-45bf-9f6c-e26baec7efcb", "historyId": "4e09b37512588899ff5513d6ffa4f4d3", "testCaseId": "5c75a1eed389171d3af356108f950d72", "fullName": "tests.test_a1_login.TestLogin#test_login_1_error_2", "labels": [{"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_a1_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-U13POE8"}, {"name": "thread", "value": "6480-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_a1_login"}]}